FROM docker.io/library/python:3.12-slim-bookworm

ARG HTTP_PROXY
ARG HTTPS_PROXY
ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV API_HOST=0.0.0.0
ENV DOCKER=true
ENV TZ=Asia/Shanghai
EXPOSE 40432
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    unzip \
    curl \
    build-essential && \
    \
    mkdir -p /app/data/font && \
    FONT_URL="https://mirrors.bfsu.edu.cn/pypi/web/packages/ad/97/03cd0a15291c6c193260d97586c4adf37a7277d8ae4507d68566c5757a6a/bbot_fonts-0.1.1-py3-none-any.whl" && \
    wget -O /tmp/bbot_fonts.whl $FONT_URL && \
    unzip /tmp/bbot_fonts.whl bbot_fonts/font/* -d /tmp/font_temp && \
    mv /tmp/font_temp/bbot_fonts/font/* /app/data/font/ && \
    rm -rf /tmp/bbot_fonts.whl /tmp/font_temp && \
    \
    apt-get purge -y --auto-remove build-essential wget unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY docker-requirements.txt .
RUN pip install --no-cache-dir -r docker-requirements.txt

RUN playwright install firefox --with-deps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./src ./src
COPY ./pyproject.toml .
COPY ./README.md .
COPY ./start_server.py .
RUN pip install --no-cache-dir -e .

HEALTHCHECK --interval=60s --timeout=2s --start-period=30s --retries=5 CMD curl -f http://localhost:40432/health || exit 1

CMD ["python", "start_server.py"]